local M = {}

---@type carvion.HighlightsFn
function M.get(opts, c)
  return {
    Comment = { fg = c.specials.comment, style = opts.styles.comments },
    ColorColumn = { bg = c.bg.cursorline },
    Conceal = { fg = c.fg.subtle },
    Cursor = { fg = c.fg.alternative, bg = c.colors.orange.base },
    lCursor = "Cursor",
    CursorIM = "Cursor",
    CursorColumn = { bg = c.bg.cursorline },
    CursorLine = "CursorColumn",
    Directory = { fg = c.colors.blue.base },

    DiffAdd = { fg = c.diagnostics.hint.fg, bg = c.diagnostics.hint.bg },
    DiffChange = { fg = c.diagnostics.info.fg, bg = c.diagnostics.info.bg },
    DiffDelete = { fg = c.diagnostics.error.fg, bg = c.diagnostics.error.bg },
    DiffText = { fg = c.fg.default, bg = c.bg.option },

    EndOfBuffer = { fg = c.bg.default },
    ErrorMsg = { fg = c.diagnostics.error.fg },
    VertSplit = { fg = c.border.default },
    WinSeparator = "VertSplit",
    Folded = { fg = c.fg.subtle, bg = c.bg.subtle },
    FoldColumn = { fg = c.fg.subtle, bg = opts.transparent and c.none or c.bg.default },
    SignColumn = { fg = c.bg.default, bg = opts.transparent and c.specials.none or c.bg.default },
    SignColumnSB = { fg = c.fg.default, bg = c.bg.sidebar },
    Substitute = { fg = c.fg.alternative, bg = c.colors.orange.soft },
    LineNr = { fg = c.specials.comment },
    CursorLineNr = { fg = c.colors.orange.base, bg = c.bg.cursorline },
    LineNrAbove = "LineNr",
    LineNrBelow = "LineNr",
    MatchParen = { fg = c.colors.orange.base, bold = true },
    ModeMsg = { fg = c.colors.blue.base, bold = true },
    MsgArea = { fg = c.fg.default },
    MoreMsg = { fg = c.colors.green.base },
    NonText = { fg = c.fg.disabled },
    Normal = { fg = c.fg.default, bg = opts.transparent and c.none or c.bg.default },
    NormalNC = { fg = c.fg.default, bg = opts.transparent and c.specials.none or c.bg.subtle },
    NormalSB = { fg = c.fg.default, bg = c.bg.sidebar },
    NormalFloat = { fg = c.fg.default, bg = c.bg.subtle },
    FloatBorder = { fg = c.border.default, bg = c.bg.subtle },
    FloatTitle = { fg = c.colors.orange.base, bg = c.bg.subtle, bold = true },
    Pmenu = { fg = c.fg.default, bg = c.bg.subtle },
    PmenuMatch = { fg = c.colors.orange.base, bold = true },
    PmenuSel = { fg = c.fg.default, bg = c.bg.option },
    PmenuMatchSel = "PmenuMatch",
    PmenuSbar = { bg = c.bg.scrollbar },
    PmenuThumb = { bg = c.border.strong },
    Question = { fg = c.colors.blue.base },
    QuickFixLine = { bg = c.bg.visual },
    Search = { fg = c.fg.alternative, bg = c.colors.orange.dim },
    IncSearch = { fg = c.fg.alternative, bg = c.colors.orange.base, bold = true },
    CurSearch = "IncSearch",
    SpecialKey = { fg = c.specials.whitespace },
    SpellBad = { sp = c.diagnostics.error.fg, undercurl = true },
    SpellCap = { sp = c.diagnostics.warn.fg, undercurl = true },
    SpellLocal = { sp = c.diagnostics.info.fg, undercurl = true },
    SpellRare = { sp = c.diagnostics.hint.fg, undercurl = true },
    StatusLine = { fg = c.fg.default, bg = c.bg.statusline },
    StatusLineNC = { fg = c.fg.muted, bg = c.bg.inactive },
    TabLine = { fg = c.fg.disabled, bg = c.bg.default },
    TabLineFill = "TabLine",
    TabLineSel = { fg = c.fg.alternative, bg = c.colors.orange.base },
    Title = { fg = c.colors.orange.base, bold = true },
    Visual = { bg = c.bg.visual },
    VisualNOS = { bg = c.bg.visual },
    WarningMsg = { fg = c.colors.orange.soft },
    Whitespace = { fg = c.specials.whitespace },
    WildMenu = { fg = c.fg.default, bg = c.bg.option },
    WinBar = "StatusLine",
    WinBarNC = "StatusLineNC",

    Bold = { fg = c.fg.default, bold = true },
    Character = { fg = c.colors.green.base },
    Constant = { fg = c.colors.neutral.base },
    Debug = { fg = c.colors.orange.base },
    Delimiter = { fg = c.specials.symbol },
    Error = { fg = c.diagnostics.error.fg, bold = true },
    Function = { fg = c.colors.orange.base, style = opts.styles.functions },
    Identifier = { fg = c.fg.default, style = opts.styles.variables },
    Italic = { fg = c.fg.default, italic = true },
    Keyword = { fg = c.specials.keyword, style = opts.styles.keywords },
    Operator = { fg = c.specials.symbol },
    PreProc = { fg = c.specials.keyword },
    Special = { fg = c.specials.symbol },
    Statement = { fg = c.specials.keyword },
    String = { fg = c.colors.green.base, style = opts.styles.strings },
    Todo = { fg = c.fg.default, bold = true },
    Type = { fg = c.colors.blue.base, style = opts.styles.types },
    Underlined = { underline = true },
    debugBreakpoint = { fg = c.diagnostics.info.fg },
    debugPC = { bg = c.bg.option },
    dosIniLabel = { fg = c.colors.orange.base },
    helpCommand = { fg = c.colors.orange.base },
    htmlH1 = { fg = c.colors.orange.base },
    htmlH2 = "htmlH1",
    qfFileName = { fg = c.colors.blue.base },
    qfLineNr = { fg = c.colors.neutral.base },

    LspReferenceText = { fg = "red", bg = c.bg.option },
    LspReferenceRead = { bg = c.bg.option },
    LspReferenceWrite = { bg = c.bg.option },
    LspSignatureActiveParameter = { bg = c.bg.visual },
    LspCodeLens = { fg = c.fg.disabled },
    LspCodeLensSeparator = { fg = c.fg.faint },
    LspInlayHint = { fg = c.diagnostics.hint.fg },
    LspInfoBorder = { fg = c.fg.default, bg = c.bg.subtle },
    ComplHint = { fg = c.colors.blue.base },

    DiagnosticError = { fg = c.diagnostics.error.fg },
    DiagnosticWarn = { fg = c.diagnostics.warn.fg },
    DiagnosticInfo = { fg = c.diagnostics.info.fg },
    DiagnosticHint = { fg = c.diagnostics.hint.fg },
    DiagnosticUnnecessary = { fg = c.colors.orange.dim },
    DiagnosticVirtualTextError = { fg = c.diagnostics.error.fg, bg = c.diagnostics.error.bg },
    DiagnosticVirtualTextWarn = { fg = c.diagnostics.warn.fg, bg = c.diagnostics.warn.bg },
    DiagnosticVirtualTextInfo = { fg = c.diagnostics.info.fg, bg = c.diagnostics.info.bg },
    DiagnosticVirtualTextHint = { fg = c.diagnostics.hint.fg, bg = c.diagnostics.hint.bg },
    DiagnosticUnderlineError = { sp = c.diagnostics.error.fg, undercurl = true },
    DiagnosticUnderlineWarn = { sp = c.diagnostics.warn.fg, undercurl = true },
    DiagnosticUnderlineInfo = { sp = c.diagnostics.info.fg, undercurl = true },
    DiagnosticUnderlineHint = { sp = c.diagnostics.hint.fg, undercurl = true },

    -- Health
    healthError = { fg = c.diagnostics.error.fg },
    healthSuccess = { fg = c.diagnostics.hint.fg },
    healthWarning = { fg = c.diagnostics.warn.fg },

    -- diff
    diffAdded = { fg = c.diagnostics.hint.fg },
    diffRemoved = { fg = c.diagnostics.error.fg },
    diffChanged = { fg = c.diagnostics.info.fg },

    diffOldFile = { fg = c.specials.comment },
    diffNewFile = { fg = c.colors.green.base },
    diffFile = { fg = c.colors.blue.base },
    diffLine = { fg = c.specials.comment },
    diffIndexLine = { fg = c.colors.neutral.base },
    helpExample = { fg = c.specials.comment },
  }
end

return M
